# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake Multi-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up build directories
        run: |
          mkdir build
          mkdir examples/build
          mkdir src/tests/build
        shell: bash
      - name: Configure and install main project (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          cmake --install .
        working-directory: build
      - name: Configure and install main project (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          cmake --install . --config Release
        working-directory: build
      - name: Configure examples (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake -DCUSTOM_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release ..
        working-directory: examples/build
      - name: Configure examples (Windows)
        if: runner.os == 'Windows'
        run: cmake -DCUSTOM_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release ..
        working-directory: examples/build
      - name: Build examples (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake --build .
        working-directory: examples/build
      - name: Build examples (Windows)
        if: runner.os == 'Windows'
        run: cmake --build . --config Release
        working-directory: examples/build
      - name: Run example tests (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          ./bin/tsstack_example
          ./bin/stack_example
        working-directory: examples/build
      - name: Run example tests (Windows)
        if: runner.os == 'Windows'
        run: |
          .\bin\tsstack_example.exe
          .\bin\stack_example.exe
        working-directory: examples/build
      - name: Build and run unit tests (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cmake ..
          cmake --build .
          ./bin/tsstack_test
        working-directory: src/tests/build
      - name: Build and run unit tests (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake ..
          cmake --build . --config Release
          .\Release\tsstack_test.exe
        working-directory: src/tests/build
